language: generic 

# anytime we use docker, we need admin rights, hence sudo.
sudo: required
services:
  - docker
  # Travis CI will install a copy of docker

before_install:
  - docker build -t piyush17/docker-react -f Dockerfile.dev .
  # a series of different commands to be executed before the tests are ran 
  # or before the project is deployed
  # add a tag to refer it later. docker_user_name/repo_name

# to run the test scripts

script:
  - docker run -e CI=true piyush17/docker-react npm run test -- --coverage
  # npm run test expects user to give an input on what to do next. We do not want that, hence   
  # we have added -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  # the name of the app will be the same as in the elastic bean stalk instance
  env: "DockerReact-env"
  # the name of the environment in the EBS instance
  bucket_name: "elasticbeanstalk-eu-central-1-773389584439"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  
