## Base image
FROM node:alpine

WORKDIR '/app'

## Copy the package.json to the workdir /app
COPY package.json .

RUN npm install

## After installing all the dependencies, 
## copy over everything else apart from the package.json file

COPY . .

CMD ["npm", "run", "start"]
