version: '3'
services:
  web:
    stdin_open: true
    build:
      context: . # from where the files are coming
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app # map pwd to /app
    # use environment if on Windows and your code is not automaticaly reflected inside the container.
    #environment:
      #- CHOKIDAR_USEPOLLING=true
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
